DATASET:
    NAME: "ade20k"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
    MODE: 'val'
TRAIN:
    EPOCHS: 10
    BATCH_SIZE: 2
    CROP_SIZE: 512
    BASE_SIZE: 520
    PRETRAINED_MODEL_PATH: "pretrained_weights/deeplabv3plus_r101-d8_512x512_80k_ade20k_20200615_014139-d5730af7.pth"
    ALPHA: 0

TEST:
    BATCH_SIZE: 1
    CROP_SIZE: 512
    IMG_SCALE: (512, 2048)

SOLVER:
    LR: 0.01
    LOSS_NAME: "cce_alpha"
    STEP:
        DECAY_EPOCH: [4, 8]

MODEL:
    MODEL_NAME: "DeepLabV3_Plus"
    BACKBONE: "resnet101"
    MMSEG_CONFIG: "mmseg-configs/deeplabv3plus_r101-d8_512x512_80k_ade20k.py"
