DATASET:
    NAME: "cityscape"
    # in rgb format
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
TRAIN:
    EPOCHS: 400
    BATCH_SIZE: 4
    CROP_SIZE: 769
TEST:
    BATCH_SIZE: 4
    CROP_SIZE: (1080, 1920)
    TEST_MODEL_PATH: weights/deeplabv3_plus_resnet101_segmentron.pth

SOLVER:
    LR: 0.02

MODEL:
    MODEL_NAME: "DeepLabV3_Plus"
    BACKBONE: "resnet101"

CRF:
    ITER_MAX: 10
    POS_XY_STD: 1
    POS_W: 3
    BI_XY_STD: 67
    BI_RGB_STD: 3
    BI_W: 4
    

