DATASET:
    NAME: "cityscape"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
    WORKERS: 8
    NOISY_NAME: "cityscape_noisy"
TRAIN:
    EPOCHS: 10
    BATCH_SIZE: 4
    CROP_SIZE: 769
    PRETRAINED_MODEL_PATH: runs/checkpoints/FCN_resnet101_cityscape_2021-02-27-02-27/best_model.pth
    MODEL_SAVE_DIR: "weights/finetune"
    ALPHA: 0.1
    
TEST:
    BATCH_SIZE: 1
    CROP_SIZE: (1025, 2049)

SOLVER:
    # LR: 0.02
    # STEP:
    #     DECAY_EPOCH: [100, 200, 300]
    LR: 0.01 # initially started with 0.02, so while finetuning it should be less.
    LOSS_NAME: "cce_alpha"
    STEP:
        DECAY_EPOCH: [4, 8]

MODEL:
    MODEL_NAME: "FCN"
    BACKBONE: "resnet101"
